#!/usr/bin/env bash

echo GROUP_ENV:
echo $GROUP_ENV
echo GROUP_ENV_SPACES:
echo $GROUP_ENV_SPACES
echo GROUP_ENV_PLAIN:
echo $GROUP_ENV_PLAIN

echo SERVICE_ENV:
echo $SERVICE_ENV
echo SERVICE_ENV_SPACES:
echo $SERVICE_ENV_SPACES
echo SERVICE_ENV_PLAIN:
echo $SERVICE_ENV_PLAIN
